[phases.setup]
nixPkgs = ["python311", "postgresql", "redis"]

[phases.install]
cmds = [
  "python --version",
  "pip --version", 
  "pip install -r requirements.txt"
]

[phases.build]
cmds = [
  "python -m alembic upgrade head",
  "python verify_deployment.py"
]

[start]
cmd = "uvicorn app.main:app --host 0.0.0.0 --port $PORT"
