[build]
builder = "nixpacks"

[deploy]
startCommand = "python start.py"
healthcheckPath = "/health"
healthcheckTimeout = 300
restartPolicyType = "on_failure"
restartPolicyMaxRetries = 3

[phases.setup]
nixPkgs = ["python311", "postgresql", "redis"]

[phases.install]
cmds = [
  "python --version",
  "pip --version", 
  "pip install -r requirements.txt"
]

[phases.build]
cmds = [
  "python diagnose_railway.py",
  "python -m alembic upgrade head",
  "python setup_database.py",
  "python verify_deployment.py"
]
