"""Initial migration

Revision ID: 5f05349437be
Revises: 
Create Date: 2025-08-13 21:41:48.504695

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5f05349437be'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('projects',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('repo_url', sa.String(length=500), nullable=False),
    sa.Column('plan_path', sa.String(length=255), nullable=True),
    sa.Column('status', sa.Enum('green', 'yellow', 'red', 'processing', 'failed', name='project_status'), nullable=True),
    sa.Column('last_updated', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('repo_url')
    )
    op.create_index('idx_projects_last_updated', 'projects', ['last_updated'], unique=False)
    op.create_index('idx_projects_status', 'projects', ['status'], unique=False)
    op.create_table('progress_snapshots',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('project_id', sa.UUID(), nullable=False),
    sa.Column('percentage_complete', sa.DECIMAL(precision=5, scale=2), nullable=True),
    sa.Column('tasks_total', sa.Integer(), nullable=True),
    sa.Column('tasks_done', sa.Integer(), nullable=True),
    sa.Column('tasks_doing', sa.Integer(), nullable=True),
    sa.Column('tasks_todo', sa.Integer(), nullable=True),
    sa.Column('tasks_blocked', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_snapshots_created_at', 'progress_snapshots', ['created_at'], unique=False)
    op.create_index('idx_snapshots_project_id', 'progress_snapshots', ['project_id'], unique=False)
    op.create_table('skills',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('project_id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('category', sa.String(length=100), nullable=True),
    sa.Column('source', sa.String(length=255), nullable=True),
    sa.Column('confidence', sa.DECIMAL(precision=3, scale=2), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_skills_category', 'skills', ['category'], unique=False)
    op.create_index('idx_skills_name', 'skills', ['name'], unique=False)
    op.create_index('idx_skills_project_id', 'skills', ['project_id'], unique=False)
    op.create_table('tasks',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('project_id', sa.UUID(), nullable=False),
    sa.Column('title', sa.Text(), nullable=False),
    sa.Column('status', sa.Enum('todo', 'doing', 'done', 'blocked', name='task_status'), nullable=True),
    sa.Column('file_path', sa.String(length=500), nullable=True),
    sa.Column('line_number', sa.Integer(), nullable=True),
    sa.Column('commit_hash', sa.String(length=40), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_tasks_file_path', 'tasks', ['file_path'], unique=False)
    op.create_index('idx_tasks_project_id', 'tasks', ['project_id'], unique=False)
    op.create_index('idx_tasks_status', 'tasks', ['status'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('idx_tasks_status', table_name='tasks')
    op.drop_index('idx_tasks_project_id', table_name='tasks')
    op.drop_index('idx_tasks_file_path', table_name='tasks')
    op.drop_table('tasks')
    op.drop_index('idx_skills_project_id', table_name='skills')
    op.drop_index('idx_skills_name', table_name='skills')
    op.drop_index('idx_skills_category', table_name='skills')
    op.drop_table('skills')
    op.drop_index('idx_snapshots_project_id', table_name='progress_snapshots')
    op.drop_index('idx_snapshots_created_at', table_name='progress_snapshots')
    op.drop_table('progress_snapshots')
    op.drop_index('idx_projects_status', table_name='projects')
    op.drop_index('idx_projects_last_updated', table_name='projects')
    op.drop_table('projects')
    # ### end Alembic commands ###
